# Copy from OpenDAL
name: Setup Rust Builder
description: 'Prepare Rust Build Environment'

runs:
  using: "composite"
  steps:
    - name: Cache Cargo
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          ${{ runner.os }}-cargo
    - name: Setup rust related environment variables
      shell: bash
      # FIXME: using toolchain nightly version
      run: rustup update nightly